# Generated by Django 3.1 on 2020-08-06 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 7, 44, 5, 127443, tzinfo=utc)),
        ),
    ]
